-- Authored content: original texts filling gaps the open textbooks do not cover.
-- Everything is origin='ai_generated' - there is no source to quote.
-- Written as plain independent statements, no nested CTEs: that is the shape
-- the Supabase SQL editor is known to accept for this project.

insert into public.content_sources (title, author, source_url, license, license_url, parser, parser_config, status)
values ('Yuny authored content (English)', 'Yuny', 'yuny://authored/en/v1', 'Proprietary - Yuny original content, not an open educational resource', null, 'authored', '{}'::jsonb, 'ready')
on conflict (source_url) do update set status = 'ready', license = excluded.license;

-- ===== Booking a place to stay (A2) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-booking-a-room', 'chapter', 'Booking a place to stay', 0, '[{"type":"paragraph","text":"Marta wants to visit Lisbon in April. She has five days and a small budget, so she looks for a cheap place to stay."},{"type":"paragraph","text":"First she opens a booking website. She types the city and the dates. The website shows hotels, hostels and apartments."},{"type":"paragraph","text":"A hotel near the centre costs 120 euros a night. That is too expensive for Marta."},{"type":"paragraph","text":"A hostel costs 25 euros a night, but she must share a room with five other people. Marta does not sleep well when a room is noisy."},{"type":"paragraph","text":"Then she finds a small guesthouse. It costs 45 euros a night. The room is private and breakfast is included. The guesthouse is twenty minutes from the centre by bus."},{"type":"paragraph","text":"Marta reads the reviews. Other guests write that the beds are comfortable and the owner is friendly. One guest writes that the walls are thin."},{"type":"paragraph","text":"She decides to book the guesthouse for four nights. She pays with her card and receives an email. The email is her confirmation."},{"type":"paragraph","text":"Marta prints the confirmation. She wants to show it when she arrives."}]'::jsonb, now(), 177, 'parsed', 'A2'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'topic', 'travel-and-accommodation', '{"label":"travel-and-accommodation"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'vocabulary', 'budget', '{"word":"budget","definition":"the amount of money you can spend on something"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'budget'), 'fill_blank', '{"sentence_with_blank":"Marta cannot pay 120 euros a night because she has a small ___.","accepted_answers":["budget"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'vocabulary', 'guesthouse', '{"word":"guesthouse","definition":"a small house where travellers pay to sleep, smaller than a hotel"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'guesthouse'), 'fill_blank', '{"sentence_with_blank":"It is not a hotel and not a hostel, but a small ___.","accepted_answers":["guesthouse"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'vocabulary', 'review', '{"word":"review","definition":"what a customer writes about a place or product after using it"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'review'), 'fill_blank', '{"sentence_with_blank":"Before booking, she reads every ___ written by other guests.","accepted_answers":["review"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'vocabulary', 'confirmation', '{"word":"confirmation","definition":"a message that proves your booking is complete"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'confirmation'), 'fill_blank', '{"sentence_with_blank":"After she pays, the website sends an email with her ___.","accepted_answers":["confirmation"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'vocabulary', 'included', '{"word":"included","definition":"already part of the price, with nothing more to pay"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'included'), 'fill_blank', '{"sentence_with_blank":"Breakfast is ___ in the price, so she pays nothing extra for it.","accepted_answers":["included"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'grammar', 'Comparatives for prices: cheaper than, more expensive than', '{"point":"Comparatives for prices: cheaper than, more expensive than","explanation":"Use -er than for short adjectives and more ... than for longer ones: A hostel is cheaper than a hotel. A hotel is more expensive than a guesthouse."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'grammar' and ki.dedup_key = 'Comparatives for prices: cheaper than, more expensive than'), 'multiple_choice', '{"prompt":"The hostel is ___ than the hotel.","options":["more cheap","cheap","cheaper","cheapest"],"correct_index":2}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'grammar', 'Must for necessity', '{"point":"Must for necessity","explanation":"Use ''must'' plus a bare verb for something necessary: She must share a room with five other people."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room') and ki.kind = 'grammar' and ki.dedup_key = 'Must for necessity'), 'multiple_choice', '{"prompt":"In a hostel you ___ share a room.","options":["musts","are must","must to","must"],"correct_index":3}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'example', 'authored-booking-a-room-ex0', '{"sentence":"A hotel near the centre costs 120 euros a night."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), 'example', 'authored-booking-a-room-ex1', '{"sentence":"She decides to book the guesthouse for four nights."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-booking-a-room'), (select id from public.topics where slug = 'travel-and-accommodation'))
on conflict do nothing;

-- ===== Checking in at the hotel (A2) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-checking-in', 'chapter', 'Checking in at the hotel', 1, '[{"type":"paragraph","text":"Marta arrives in Lisbon on Friday afternoon. She takes a bus from the airport and walks to the guesthouse."},{"type":"paragraph","text":"A man is standing behind the desk. \"Good afternoon. Do you have a reservation?\" he asks."},{"type":"paragraph","text":"\"Yes,\" says Marta. \"My name is Marta Silva. I booked a single room for four nights.\""},{"type":"paragraph","text":"The man looks at his computer. \"I have it here. Can I see your passport, please?\""},{"type":"paragraph","text":"Marta gives him her passport. He writes down the number and gives it back."},{"type":"paragraph","text":"\"Your room is number 12, on the second floor. Here is the key. Breakfast is from seven until ten in the small room next to the entrance.\""},{"type":"paragraph","text":"\"Thank you. What time do I have to leave on Tuesday?\" Marta asks."},{"type":"paragraph","text":"\"Check-out is at eleven o''clock. If you need a later time, please tell us the day before.\""},{"type":"paragraph","text":"Marta takes her key and goes upstairs. The room is small but clean, and the window looks out over a narrow street."}]'::jsonb, now(), 160, 'parsed', 'A2'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'topic', 'travel-and-accommodation', '{"label":"travel-and-accommodation"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'vocabulary', 'reservation', '{"word":"reservation","definition":"an arrangement made in advance to keep a room or table for you"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'vocabulary' and ki.dedup_key = 'reservation'), 'fill_blank', '{"sentence_with_blank":"The receptionist asks whether she has a ___ before looking at his computer.","accepted_answers":["reservation"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'vocabulary', 'passport', '{"word":"passport","definition":"an official document that lets you travel between countries"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'vocabulary' and ki.dedup_key = 'passport'), 'fill_blank', '{"sentence_with_blank":"At the desk they ask to see her ___ to check who she is.","accepted_answers":["passport"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'vocabulary', 'floor', '{"word":"floor","definition":"one level of a building"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'vocabulary' and ki.dedup_key = 'floor'), 'fill_blank', '{"sentence_with_blank":"Her room is number 12, on the second ___.","accepted_answers":["floor"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'vocabulary', 'check-out', '{"word":"check-out","definition":"the time by which you must leave your room"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'vocabulary' and ki.dedup_key = 'check-out'), 'fill_blank', '{"sentence_with_blank":"___ is at eleven o''clock, so she must leave before then.","accepted_answers":["check-out"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'vocabulary', 'entrance', '{"word":"entrance","definition":"the door or gate where you go into a building"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'vocabulary' and ki.dedup_key = 'entrance'), 'fill_blank', '{"sentence_with_blank":"Breakfast is served in a small room next to the ___.","accepted_answers":["entrance"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'grammar', 'Polite requests with Can I ... please?', '{"point":"Polite requests with Can I ... please?","explanation":"Use ''Can I'' plus a bare verb for a polite request: Can I see your passport, please?"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'grammar' and ki.dedup_key = 'Polite requests with Can I ... please?'), 'multiple_choice', '{"prompt":"___ see your passport, please?","options":["Can I","Do I can","I can","Can I to"],"correct_index":0}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'grammar', 'Prepositions of time: from ... until, at', '{"point":"Prepositions of time: from ... until, at","explanation":"Use ''from X until Y'' for a period and ''at'' for a point in time: Breakfast is from seven until ten. Check-out is at eleven."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in') and ki.kind = 'grammar' and ki.dedup_key = 'Prepositions of time: from ... until, at'), 'multiple_choice', '{"prompt":"Breakfast is ___ seven until ten.","options":["from","since","on","during"],"correct_index":0}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'example', 'authored-checking-in-ex0', '{"sentence":"\"Do you have a reservation?\" he asks."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), 'example', 'authored-checking-in-ex1', '{"sentence":"Check-out is at eleven o''clock."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-checking-in'), (select id from public.topics where slug = 'travel-and-accommodation'))
on conflict do nothing;

-- ===== Asking for directions (A2) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-asking-directions', 'chapter', 'Asking for directions', 2, '[{"type":"paragraph","text":"On Saturday morning Marta wants to visit the castle. She has a paper map, but the streets are narrow and she quickly gets lost."},{"type":"paragraph","text":"She stops an older woman near a bakery. \"Excuse me, how do I get to the castle?\""},{"type":"paragraph","text":"\"It is not far,\" the woman says. \"Go straight along this street to the end. Then turn left at the church.\""},{"type":"paragraph","text":"\"Left at the church,\" Marta repeats."},{"type":"paragraph","text":"\"Yes. After the church you will see some steps. Go up the steps and turn right. The castle is at the top of the hill.\""},{"type":"paragraph","text":"\"Is it far on foot?\""},{"type":"paragraph","text":"\"About fifteen minutes, but the hill is steep. If you are tired, you can take tram 28. The stop is behind you, opposite the pharmacy.\""},{"type":"paragraph","text":"Marta thanks her and decides to walk. She goes straight, turns left at the church and finds the steps."},{"type":"paragraph","text":"Twenty minutes later she is standing at the castle wall, looking down at the red roofs of the city."}]'::jsonb, now(), 161, 'parsed', 'A2'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'topic', 'transport-and-directions', '{"label":"transport-and-directions"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'vocabulary', 'lost', '{"word":"lost","definition":"not knowing where you are or which way to go"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'vocabulary' and ki.dedup_key = 'lost'), 'fill_blank', '{"sentence_with_blank":"The streets are narrow and confusing, so Marta quickly gets ___.","accepted_answers":["lost"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'vocabulary', 'straight', '{"word":"straight","definition":"continuing in one direction without turning"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'vocabulary' and ki.dedup_key = 'straight'), 'fill_blank', '{"sentence_with_blank":"The woman tells her to go ___ along the street to the end.","accepted_answers":["straight"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'vocabulary', 'steps', '{"word":"steps","definition":"a set of flat surfaces you walk up or down"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'vocabulary' and ki.dedup_key = 'steps'), 'fill_blank', '{"sentence_with_blank":"After the church she must go up the stone ___ to reach the hill.","accepted_answers":["steps"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'vocabulary', 'steep', '{"word":"steep","definition":"rising or falling sharply, hard to walk up"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'vocabulary' and ki.dedup_key = 'steep'), 'fill_blank', '{"sentence_with_blank":"The hill is very ___, so walking up takes effort.","accepted_answers":["steep"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'vocabulary', 'opposite', '{"word":"opposite","definition":"on the other side, directly facing something"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'vocabulary' and ki.dedup_key = 'opposite'), 'fill_blank', '{"sentence_with_blank":"The tram stop is ___ the pharmacy, on the other side of the road.","accepted_answers":["opposite"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'grammar', 'Imperatives for directions', '{"point":"Imperatives for directions","explanation":"Directions use the bare verb with no subject: Go straight. Turn left at the church. Take tram 28."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'grammar' and ki.dedup_key = 'Imperatives for directions'), 'multiple_choice', '{"prompt":"___ left at the church.","options":["Turns","You turning","To turn","Turn"],"correct_index":3}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'grammar', 'First conditional: if + present, will/can', '{"point":"First conditional: if + present, will/can","explanation":"Use ''if'' plus the present simple for a real possibility: If you are tired, you can take the tram."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions') and ki.kind = 'grammar' and ki.dedup_key = 'First conditional: if + present, will/can'), 'multiple_choice', '{"prompt":"If you ___ tired, you can take the tram.","options":["would be","are","will be","are being"],"correct_index":1}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'example', 'authored-asking-directions-ex0', '{"sentence":"\"Excuse me, how do I get to the castle?\""}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), 'example', 'authored-asking-directions-ex1', '{"sentence":"Go straight along this street to the end."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), (select id from public.topics where slug = 'transport-and-directions'))
on conflict do nothing;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-asking-directions'), (select id from public.topics where slug = 'city-and-places'))
on conflict do nothing;

-- ===== A problem with the room (B1) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-problem-with-room', 'chapter', 'A problem with the room', 3, '[{"type":"paragraph","text":"On the second night Marta hardly slept. The guests in the next room came back after midnight and talked loudly until three in the morning. The guest who had warned about thin walls in the review had not been exaggerating."},{"type":"paragraph","text":"At breakfast she thought about what to do. She could say nothing and hope the next night would be quieter, or she could complain. She had never enjoyed complaining, but four nights of no sleep would ruin the trip."},{"type":"paragraph","text":"She went to the desk and explained the problem calmly. \"I understand it is not your fault,\" she said, \"but I have not slept properly since I arrived. Is there another room available?\""},{"type":"paragraph","text":"The receptionist checked the computer and apologised. The guesthouse was full that night, but a room at the back would be free from the following afternoon. It was slightly smaller and had no view, though it was much quieter."},{"type":"paragraph","text":"\"I would rather have a quiet room than a view,\" Marta said."},{"type":"paragraph","text":"He moved her booking and offered her a free breakfast for the trouble. If she had said nothing, she would have spent three more bad nights."},{"type":"paragraph","text":"Later she added her own review. She wrote that the walls were thin, but that the staff had solved the problem quickly and politely. Both parts of that, she thought, were worth knowing."}]'::jsonb, now(), 222, 'parsed', 'B1'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'topic', 'travel-and-accommodation', '{"label":"travel-and-accommodation"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'vocabulary', 'complain', '{"word":"complain","definition":"to tell someone officially that you are not satisfied"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'complain'), 'fill_blank', '{"sentence_with_blank":"She dislikes making a fuss, but decides to ___ about the noise.","accepted_answers":["complain"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'vocabulary', 'available', '{"word":"available","definition":"free to be used or taken"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'available'), 'fill_blank', '{"sentence_with_blank":"She asks the receptionist whether another room is ___ tonight.","accepted_answers":["available"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'vocabulary', 'apologise', '{"word":"apologise","definition":"to say you are sorry for something"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'apologise'), 'fill_blank', '{"sentence_with_blank":"The receptionist checks the computer and begins to ___ for the noise.","accepted_answers":["apologise"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'vocabulary', 'exaggerate', '{"word":"exaggerate","definition":"to describe something as larger or worse than it really is"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'exaggerate'), 'fill_blank', '{"sentence_with_blank":"The earlier guest had not been wrong and did not ___ about the thin walls.","accepted_answers":["exaggerate"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'vocabulary', 'staff', '{"word":"staff","definition":"the people who work at a place"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'vocabulary' and ki.dedup_key = 'staff'), 'fill_blank', '{"sentence_with_blank":"In her review she praises the ___ for solving the problem quickly.","accepted_answers":["staff"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'grammar', 'Present perfect with since and for', '{"point":"Present perfect with since and for","explanation":"Use the present perfect for something that started in the past and continues now: I have not slept properly since I arrived."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'grammar' and ki.dedup_key = 'Present perfect with since and for'), 'multiple_choice', '{"prompt":"I ___ properly since I arrived.","options":["haven''t slept","didn''t sleep","don''t sleep","am not sleeping"],"correct_index":0}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'grammar', 'Third conditional for unreal past', '{"point":"Third conditional for unreal past","explanation":"Use ''if'' plus past perfect with ''would have'' for something that did not happen: If she had said nothing, she would have spent three more bad nights."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'grammar' and ki.dedup_key = 'Third conditional for unreal past'), 'multiple_choice', '{"prompt":"If she ___ nothing, she would have slept badly again.","options":["would say","has said","said","had said"],"correct_index":3}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'grammar', 'Would rather + bare infinitive', '{"point":"Would rather + bare infinitive","explanation":"Use ''would rather'' plus a bare verb to state a preference: I would rather have a quiet room than a view."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room') and ki.kind = 'grammar' and ki.dedup_key = 'Would rather + bare infinitive'), 'multiple_choice', '{"prompt":"I would rather ___ a quiet room than a view.","options":["have","having","to have","had to have"],"correct_index":0}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'example', 'authored-problem-with-room-ex0', '{"sentence":"I have not slept properly since I arrived."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), 'example', 'authored-problem-with-room-ex1', '{"sentence":"I would rather have a quiet room than a view."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), (select id from public.topics where slug = 'travel-and-accommodation'))
on conflict do nothing;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-problem-with-room'), (select id from public.topics where slug = 'feelings-and-opinions'))
on conflict do nothing;

-- ===== Buying a train ticket (B1) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-buying-a-ticket', 'chapter', 'Buying a train ticket', 4, '[{"type":"paragraph","text":"Marta had planned to spend her last full day in Sintra, a town about forty minutes from Lisbon by train. She reached the station early, expecting a queue, and found one."},{"type":"paragraph","text":"The machines took cards but only sold single tickets, and the screen was in Portuguese. Rather than guess, she joined the shorter queue at the ticket office."},{"type":"paragraph","text":"\"A return to Sintra, please. Is there a cheaper option if I come back this evening?\""},{"type":"paragraph","text":"\"A day return is cheaper than two singles,\" the clerk said. \"It is valid until midnight, but only on regional trains. If you take an express, you will have to pay a supplement.\""},{"type":"paragraph","text":"Marta bought the day return. The clerk pointed at the departure board and told her that trains left every twenty minutes from platform four."},{"type":"paragraph","text":"She had almost boarded the wrong train when a guard stopped her: that one went to Cascais. The two lines leave from the same platform, and the difference is easy to miss unless you check the board carefully."},{"type":"paragraph","text":"By the time she found the right train, she had learned something useful. Asking a person had cost her five minutes in a queue and saved her a wasted afternoon."}]'::jsonb, now(), 199, 'parsed', 'B1'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'topic', 'transport-and-directions', '{"label":"transport-and-directions"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'vocabulary', 'queue', '{"word":"queue","definition":"a line of people waiting for their turn"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'vocabulary' and ki.dedup_key = 'queue'), 'fill_blank', '{"sentence_with_blank":"She expected to wait and found a long ___ at the machines.","accepted_answers":["queue"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'vocabulary', 'return', '{"word":"return","definition":"a ticket that takes you somewhere and back again"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'vocabulary' and ki.dedup_key = 'return'), 'fill_blank', '{"sentence_with_blank":"Instead of two singles she buys a day ___, which is cheaper.","accepted_answers":["return"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'vocabulary', 'valid', '{"word":"valid","definition":"able to be legally or officially used"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'vocabulary' and ki.dedup_key = 'valid'), 'fill_blank', '{"sentence_with_blank":"The ticket is ___ until midnight, so she can travel back late.","accepted_answers":["valid"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'vocabulary', 'supplement', '{"word":"supplement","definition":"an extra amount of money added to the basic price"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'vocabulary' and ki.dedup_key = 'supplement'), 'fill_blank', '{"sentence_with_blank":"On a faster express train she would have to pay a ___.","accepted_answers":["supplement"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'vocabulary', 'platform', '{"word":"platform","definition":"the raised area beside a railway track where you get on a train"}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'vocabulary' and ki.dedup_key = 'platform'), 'fill_blank', '{"sentence_with_blank":"Trains to Sintra leave every twenty minutes from ___ four.","accepted_answers":["platform"]}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'grammar', 'Past perfect for the earlier of two past events', '{"point":"Past perfect for the earlier of two past events","explanation":"Use had plus a past participle for what happened first: She had almost boarded the wrong train when a guard stopped her."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'grammar' and ki.dedup_key = 'Past perfect for the earlier of two past events'), 'multiple_choice', '{"prompt":"She ___ the wrong train when a guard stopped her.","options":["was almost board","almost boards","had almost boarded","has almost boarded"],"correct_index":2}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'grammar', 'Unless for negative condition', '{"point":"Unless for negative condition","explanation":"''Unless'' means ''if not'': The difference is easy to miss unless you check the board."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'grammar' and ki.dedup_key = 'Unless for negative condition'), 'multiple_choice', '{"prompt":"You will miss it ___ you check the board.","options":["in case of","if","without you","unless"],"correct_index":3}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'grammar', 'Rather than + bare infinitive', '{"point":"Rather than + bare infinitive","explanation":"Use ''rather than'' to reject one option in favour of another: Rather than guess, she joined the queue."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket') and ki.kind = 'grammar' and ki.dedup_key = 'Rather than + bare infinitive'), 'multiple_choice', '{"prompt":"___ guess, she asked at the ticket office.","options":["Better than to","Instead","Rather than","Rather to"],"correct_index":2}'::jsonb, 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'example', 'authored-buying-a-ticket-ex0', '{"sentence":"A day return is cheaper than two singles."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), 'example', 'authored-buying-a-ticket-ex1', '{"sentence":"Trains left every twenty minutes from platform four."}'::jsonb, 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), (select id from public.topics where slug = 'transport-and-directions'))
on conflict do nothing;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-buying-a-ticket'), (select id from public.topics where slug = 'travel-and-accommodation'))
on conflict do nothing;
