-- Knowledge extraction, hand-authored to stand in for the AI step
-- content-import cannot run without a key. Shapes match _shared/content.ts.
-- origin: ai_generated for authored definitions/explanations/labels;
-- source_derived for example sentences quoted verbatim from the chapter.

with u as (
  select cu.id, cu.external_id from public.content_units cu
  join public.content_sources cs on cs.id = cu.source_id
  where cs.source_url = 'https://openoregon.pressbooks.pub/portlandpeopleandplaces/'
), i(ext, kind, key, data, origin, status) as (values
('chapter-94','topic','city-and-geography','{"label":"city-and-geography"}'::jsonb,'ai_generated','draft'),
('chapter-94','vocabulary','bridge','{"word":"bridge","definition":"a structure built over a river or road so people can cross"}'::jsonb,'ai_generated','draft'),
('chapter-94','vocabulary','mountain','{"word":"mountain","definition":"a very high hill of rock"}'::jsonb,'ai_generated','draft'),
('chapter-94','vocabulary','garden','{"word":"garden","definition":"a piece of land where flowers or vegetables are grown"}'::jsonb,'ai_generated','draft'),
('chapter-94','vocabulary','vegan','{"word":"vegan","definition":"a person who eats no food that comes from animals"}'::jsonb,'ai_generated','draft'),
('chapter-94','vocabulary','state','{"word":"state","definition":"one of the regions that together form a country such as the USA"}'::jsonb,'ai_generated','draft'),
('chapter-94','grammar','Adjectives to describe weather and seasons','{"point":"Adjectives to describe weather and seasons","explanation":"Use ''be'' plus adjectives to describe seasons: Summers are warm and dry. Winters are cool and wet."}'::jsonb,'ai_generated','draft'),
('chapter-94','grammar','Possessive with of','{"point":"Possessive with of","explanation":"Use ''the name of X'' to link two nouns: The name of the mountain is Mt. Hood."}'::jsonb,'ai_generated','draft'),
('chapter-94','example','chapter-94-ex0','{"sentence":"Portland is a small city in Oregon."}'::jsonb,'source_derived','validated'),
('chapter-94','example','chapter-94-ex1','{"sentence":"Summers are warm and dry in Portland. Susan likes the sun."}'::jsonb,'source_derived','validated'),
('chapter-84','topic','hobbies','{"label":"hobbies"}'::jsonb,'ai_generated','draft'),
('chapter-84','vocabulary','hobby','{"word":"hobby","definition":"an activity you enjoy doing in your free time"}'::jsonb,'ai_generated','draft'),
('chapter-84','vocabulary','weird','{"word":"weird","definition":"strange or unusual"}'::jsonb,'ai_generated','draft'),
('chapter-84','vocabulary','trash','{"word":"trash","definition":"things people throw away because they do not want them"}'::jsonb,'ai_generated','draft'),
('chapter-84','vocabulary','brakes','{"word":"brakes","definition":"the parts that make a vehicle slow down or stop"}'::jsonb,'ai_generated','draft'),
('chapter-84','vocabulary','mask','{"word":"mask","definition":"a covering worn over the face"}'::jsonb,'ai_generated','draft'),
('chapter-84','grammar','Can for ability','{"point":"Can for ability","explanation":"Use ''can'' plus a bare verb to talk about ability: Can you play the bagpipes and ride at the same time? Yes, I can."}'::jsonb,'ai_generated','draft'),
('chapter-84','grammar','Adverbs of manner: fast, well','{"point":"Adverbs of manner: fast, well","explanation":"Adverbs describe how someone does something and usually follow the verb: He learns very fast. He rides well."}'::jsonb,'ai_generated','draft'),
('chapter-84','example','chapter-84-ex0','{"sentence":"Brian has a strange hobby. He plays the bagpipes."}'::jsonb,'source_derived','validated'),
('chapter-84','example','chapter-84-ex1','{"sentence":"He is always learning new things. He learns very fast."}'::jsonb,'source_derived','validated'),
('chapter-75','topic','city-history','{"label":"city-history"}'::jsonb,'ai_generated','draft'),
('chapter-75','vocabulary','coin','{"word":"coin","definition":"a small round piece of metal used as money"}'::jsonb,'ai_generated','draft'),
('chapter-75','vocabulary','penny','{"word":"penny","definition":"a coin of very small value"}'::jsonb,'ai_generated','draft'),
('chapter-75','vocabulary','wagon','{"word":"wagon","definition":"a vehicle with wheels pulled by animals"}'::jsonb,'ai_generated','draft'),
('chapter-75','vocabulary','museum','{"word":"museum","definition":"a building where interesting or historical objects are shown"}'::jsonb,'ai_generated','draft'),
('chapter-75','grammar','Ordinal adverbs: first, second, third','{"point":"Ordinal adverbs: first, second, third","explanation":"Use first, second and third to put events in order: First, it is heads. Second, it is tails. Third, it is heads again."}'::jsonb,'ai_generated','draft'),
('chapter-75','grammar','Want + to + verb','{"point":"Want + to + verb","explanation":"Use ''want to'' plus a verb for a wish: He wants to name the new city Portland."}'::jsonb,'ai_generated','draft'),
('chapter-75','example','chapter-75-ex0','{"sentence":"The men can''t decide. So they find a penny."}'::jsonb,'source_derived','validated'),
('chapter-75','example','chapter-75-ex1','{"sentence":"The name of the new city is Portland, Oregon."}'::jsonb,'source_derived','validated'),
('chapter-402','topic','celebrations-and-feelings','{"label":"celebrations-and-feelings"}'::jsonb,'ai_generated','draft'),
('chapter-402','vocabulary','confused','{"word":"confused","definition":"not able to understand what is happening"}'::jsonb,'ai_generated','draft'),
('chapter-402','vocabulary','surprised','{"word":"surprised","definition":"feeling sudden wonder because something was not expected"}'::jsonb,'ai_generated','draft'),
('chapter-402','vocabulary','marry','{"word":"marry","definition":"to become someone''s husband or wife"}'::jsonb,'ai_generated','draft'),
('chapter-402','vocabulary','quiet','{"word":"quiet","definition":"making little or no noise"}'::jsonb,'ai_generated','draft'),
('chapter-402','grammar','Present continuous for actions now','{"point":"Present continuous for actions now","explanation":"Use ''be'' plus verb-ing for something happening at this moment: They are singing and dancing in the street."}'::jsonb,'ai_generated','draft'),
('chapter-402','grammar','Adjectives ending -ed for feelings','{"point":"Adjectives ending -ed for feelings","explanation":"Use -ed adjectives for how a person feels: she feels confused, she is surprised."}'::jsonb,'ai_generated','draft'),
('chapter-402','example','chapter-402-ex0','{"sentence":"Amy sees her friends. She is surprised."}'::jsonb,'source_derived','validated'),
('chapter-402','example','chapter-402-ex1','{"sentence":"Then Isaac asks Amy to marry him."}'::jsonb,'source_derived','validated'),
('chapter-69','topic','immigration-and-work','{"label":"immigration-and-work"}'::jsonb,'ai_generated','draft'),
('chapter-69','vocabulary','immigrant','{"word":"immigrant","definition":"a person who comes to live in a new country"}'::jsonb,'ai_generated','draft'),
('chapter-69','vocabulary','forest','{"word":"forest","definition":"a large area covered with trees"}'::jsonb,'ai_generated','draft'),
('chapter-69','vocabulary','thirsty','{"word":"thirsty","definition":"needing something to drink"}'::jsonb,'ai_generated','draft'),
('chapter-69','vocabulary','rich','{"word":"rich","definition":"having a lot of money"}'::jsonb,'ai_generated','draft'),
('chapter-69','vocabulary','fountain','{"word":"fountain","definition":"a structure that sends out water for people to drink or look at"}'::jsonb,'ai_generated','draft'),
('chapter-69','grammar','Simple present for life stories','{"point":"Simple present for life stories","explanation":"This chapter tells a past story in the present tense to make it vivid: He leaves Norway, and he comes to the United States."}'::jsonb,'ai_generated','draft'),
('chapter-69','grammar','Comparative with more','{"point":"Comparative with more","explanation":"Use ''more'' before longer words to compare: He wants to make more money."}'::jsonb,'ai_generated','draft'),
('chapter-69','example','chapter-69-ex0','{"sentence":"Simon lives in Wisconsin. He works at a store."}'::jsonb,'source_derived','validated'),
('chapter-69','example','chapter-69-ex1','{"sentence":"Simon is very rich. He has a lot of money."}'::jsonb,'source_derived','validated'),
('chapter-127','topic','parks-and-stories','{"label":"parks-and-stories"}'::jsonb,'ai_generated','draft'),
('chapter-127','vocabulary','hole','{"word":"hole","definition":"an empty space or opening in a surface"}'::jsonb,'ai_generated','draft'),
('chapter-127','vocabulary','weed','{"word":"weed","definition":"a wild plant growing where it is not wanted"}'::jsonb,'ai_generated','draft'),
('chapter-127','vocabulary','wish','{"word":"wish","definition":"something you want very much to happen"}'::jsonb,'ai_generated','draft'),
('chapter-127','vocabulary','newspaper','{"word":"newspaper","definition":"printed sheets with news, published every day or week"}'::jsonb,'ai_generated','draft'),
('chapter-127','grammar','Superlative with the -est','{"point":"Superlative with the -est","explanation":"Use ''the'' plus -est for the top of a group: Mill Ends Park is the smallest park in the world."}'::jsonb,'ai_generated','draft'),
('chapter-127','grammar','Verbs of perception: look, see, sound','{"point":"Verbs of perception: look, see, sound","explanation":"Use ''look'' and ''see'' for what the eyes notice: He looks out his window. He sees a busy street."}'::jsonb,'ai_generated','draft'),
('chapter-127','example','chapter-127-ex0','{"sentence":"Dick is a writer. He likes to tell stories."}'::jsonb,'source_derived','validated'),
('chapter-127','example','chapter-127-ex1','{"sentence":"He pulls weeds. He plants flowers."}'::jsonb,'source_derived','validated'),
('chapter-243','topic','art-and-weather','{"label":"art-and-weather"}'::jsonb,'ai_generated','draft'),
('chapter-243','vocabulary','sculpture','{"word":"sculpture","definition":"a work of art made from stone, metal or wood"}'::jsonb,'ai_generated','draft'),
('chapter-243','vocabulary','bronze','{"word":"bronze","definition":"a hard brown metal made from copper and tin"}'::jsonb,'ai_generated','draft'),
('chapter-243','vocabulary','artist','{"word":"artist","definition":"a person who makes paintings, sculptures or other art"}'::jsonb,'ai_generated','draft'),
('chapter-243','vocabulary','tourist','{"word":"tourist","definition":"a person who travels to visit a place for pleasure"}'::jsonb,'ai_generated','draft'),
('chapter-243','grammar','Passive with was made / was built','{"point":"Passive with was made / was built","explanation":"Use was plus a past participle when the doer is less important: The sculpture was made in 1983."}'::jsonb,'ai_generated','draft'),
('chapter-243','grammar','Measurements: weighs, is ... tall','{"point":"Measurements: weighs, is ... tall","explanation":"Use ''weighs'' for weight and ''is ... tall'' for height: It weighs 460 pounds. It is 6 feet, 10 inches tall."}'::jsonb,'ai_generated','draft'),
('chapter-243','example','chapter-243-ex0','{"sentence":"It rains a lot in Portland. It usually rains 44 inches every year."}'::jsonb,'source_derived','validated'),
('chapter-243','example','chapter-243-ex1','{"sentence":"Many people take photographs with him."}'::jsonb,'source_derived','validated'),
('chapter-248','topic','natural-disasters','{"label":"natural-disasters"}'::jsonb,'ai_generated','draft'),
('chapter-248','vocabulary','flood','{"word":"flood","definition":"a large amount of water covering land that is usually dry"}'::jsonb,'ai_generated','draft'),
('chapter-248','vocabulary','destroy','{"word":"destroy","definition":"to damage something so badly that it no longer exists"}'::jsonb,'ai_generated','draft'),
('chapter-248','vocabulary','separate','{"word":"separate","definition":"to keep two things apart"}'::jsonb,'ai_generated','draft'),
('chapter-248','vocabulary','material','{"word":"material","definition":"the substance something is made from"}'::jsonb,'ai_generated','draft'),
('chapter-248','vocabulary','company','{"word":"company","definition":"a business that makes or sells things"}'::jsonb,'ai_generated','draft'),
('chapter-248','grammar','Past simple for finished events','{"point":"Past simple for finished events","explanation":"Use the past simple for something completed at a known time: The dirt wall broke on May 30, 1948. 15 people died."}'::jsonb,'ai_generated','draft'),
('chapter-248','grammar','However for contrast','{"point":"However for contrast","explanation":"''However'' introduces a contrast with the sentence before: They say the city is safe. However, the city was built quickly."}'::jsonb,'ai_generated','draft'),
('chapter-248','example','chapter-248-ex0','{"sentence":"The city is under water in less than two hours."}'::jsonb,'source_derived','validated'),
('chapter-248','example','chapter-248-ex1','{"sentence":"The city is gone. Only stories remain."}'::jsonb,'source_derived','validated'),
('chapter-253','topic','bridges-and-transport','{"label":"bridges-and-transport"}'::jsonb,'ai_generated','draft'),
('chapter-253','vocabulary','nickname','{"word":"nickname","definition":"an informal extra name for a person or place"}'::jsonb,'ai_generated','draft'),
('chapter-253','vocabulary','deck','{"word":"deck","definition":"one level of a bridge or ship"}'::jsonb,'ai_generated','draft'),
('chapter-253','vocabulary','concrete','{"word":"concrete","definition":"a hard grey building material made from cement, sand and water"}'::jsonb,'ai_generated','draft'),
('chapter-253','vocabulary','vehicle','{"word":"vehicle","definition":"a machine such as a car, bus or truck that carries people or goods"}'::jsonb,'ai_generated','draft'),
('chapter-253','vocabulary','earthquake','{"word":"earthquake","definition":"a sudden violent shaking of the ground"}'::jsonb,'ai_generated','draft'),
('chapter-253','grammar','Passive in the past: was built, was replaced','{"point":"Passive in the past: was built, was replaced","explanation":"Use was plus past participle for things done to something: It was built in 1913. The government replaced that bridge in 2016."}'::jsonb,'ai_generated','draft'),
('chapter-253','grammar','Superlatives: the oldest, the busiest, the longest','{"point":"Superlatives: the oldest, the busiest, the longest","explanation":"Use ''the'' plus -est to name the extreme of a group: the tallest bridge, the oldest highway bridge, the busiest bridge."}'::jsonb,'ai_generated','draft'),
('chapter-253','example','chapter-253-ex0','{"sentence":"Portland has many nicknames."}'::jsonb,'source_derived','validated'),
('chapter-253','example','chapter-253-ex1','{"sentence":"The St. Johns Bridge is the tallest bridge in Portland."}'::jsonb,'source_derived','validated')
)
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
select u.id, i.kind, i.key, i.data, i.origin, i.status from i join u on u.external_id = i.ext
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, origin = excluded.origin, status = excluded.status;

with u as (
  select cu.id, cu.external_id from public.content_units cu
  join public.content_sources cs on cs.id = cu.source_id
  where cs.source_url = 'https://openoregon.pressbooks.pub/portlandpeopleandplaces/'
), e(ext, kind, key, type, payload) as (values
('chapter-94','vocabulary','bridge','fill_blank','{"sentence_with_blank":"To cross the river, Susan drives over a ___.","accepted_answers":["bridge"]}'::jsonb),
('chapter-94','vocabulary','mountain','fill_blank','{"sentence_with_blank":"Mt. Hood is a tall ___ near Portland.","accepted_answers":["mountain"]}'::jsonb),
('chapter-94','vocabulary','garden','fill_blank','{"sentence_with_blank":"Susan grows roses in her ___.","accepted_answers":["garden"]}'::jsonb),
('chapter-94','vocabulary','vegan','fill_blank','{"sentence_with_blank":"She eats no meat, milk or eggs because she is ___.","accepted_answers":["vegan"]}'::jsonb),
('chapter-94','vocabulary','state','fill_blank','{"sentence_with_blank":"Oregon is a ___ in the United States.","accepted_answers":["state"]}'::jsonb),
('chapter-94','grammar','Adjectives to describe weather and seasons','multiple_choice','{"prompt":"Winters in Portland ___ cool and wet.","options":["was","is","are","be"],"correct_index":2}'::jsonb),
('chapter-94','grammar','Possessive with of','multiple_choice','{"prompt":"___ the river is the Willamette.","options":["The name from","The name of","The name to","Name of the"],"correct_index":1}'::jsonb),
('chapter-84','vocabulary','hobby','fill_blank','{"sentence_with_blank":"Playing the bagpipes is an unusual ___.","accepted_answers":["hobby"]}'::jsonb),
('chapter-84','vocabulary','weird','fill_blank','{"sentence_with_blank":"The music sounds very ___ — it is not like normal music.","accepted_answers":["weird"]}'::jsonb),
('chapter-84','vocabulary','trash','fill_blank','{"sentence_with_blank":"Brian finds the unicycle in the ___.","accepted_answers":["trash"]}'::jsonb),
('chapter-84','vocabulary','brakes','fill_blank','{"sentence_with_blank":"The unicycle has no handlebars and no ___, so it is hard to stop.","accepted_answers":["brakes"]}'::jsonb),
('chapter-84','vocabulary','mask','fill_blank','{"sentence_with_blank":"He wears a Darth Vader ___ so nobody sees his face.","accepted_answers":["mask"]}'::jsonb),
('chapter-84','grammar','Can for ability','multiple_choice','{"prompt":"\"___ you ride a unicycle?\" \"Yes, I can.\"","options":["Are","Can","Can to","Do can"],"correct_index":1}'::jsonb),
('chapter-84','grammar','Adverbs of manner: fast, well','multiple_choice','{"prompt":"Brian learns new things very ___.","options":["fast","faster than","fastly","the fast"],"correct_index":0}'::jsonb),
('chapter-75','vocabulary','coin','fill_blank','{"sentence_with_blank":"They could not decide, so they threw a ___ in the air.","accepted_answers":["coin"]}'::jsonb),
('chapter-75','vocabulary','penny','fill_blank','{"sentence_with_blank":"The two men flipped a ___ three times to choose the name.","accepted_answers":["penny"]}'::jsonb),
('chapter-75','vocabulary','wagon','fill_blank','{"sentence_with_blank":"In 1845 people travelled west in a ___ pulled by horses.","accepted_answers":["wagon"]}'::jsonb),
('chapter-75','vocabulary','museum','fill_blank','{"sentence_with_blank":"You can see the famous coin today at a ___ in downtown Portland.","accepted_answers":["museum"]}'::jsonb),
('chapter-75','grammar','Ordinal adverbs: first, second, third','multiple_choice','{"prompt":"___, it is heads. Second, it is tails.","options":["One","First","Firstly of","The one"],"correct_index":1}'::jsonb),
('chapter-75','grammar','Want + to + verb','multiple_choice','{"prompt":"Francis ___ the city Portland.","options":["wants naming","wants to name","want to name","wants name"],"correct_index":1}'::jsonb),
('chapter-402','vocabulary','confused','fill_blank','{"sentence_with_blank":"Amy does not understand why she must wear headphones. She feels ___.","accepted_answers":["confused"]}'::jsonb),
('chapter-402','vocabulary','surprised','fill_blank','{"sentence_with_blank":"She did not expect to see her friends, so she is very ___.","accepted_answers":["surprised"]}'::jsonb),
('chapter-402','vocabulary','marry','fill_blank','{"sentence_with_blank":"Isaac loves Amy and wants to ___ her.","accepted_answers":["marry"]}'::jsonb),
('chapter-402','vocabulary','quiet','fill_blank','{"sentence_with_blank":"The music stops and everyone is very ___.","accepted_answers":["quiet"]}'::jsonb),
('chapter-402','grammar','Present continuous for actions now','multiple_choice','{"prompt":"Look! Everyone ___ in the street.","options":["dance","is dance","is dancing","are dance"],"correct_index":2}'::jsonb),
('chapter-402','grammar','Adjectives ending -ed for feelings','multiple_choice','{"prompt":"Amy does not understand. She is ___.","options":["confusing","confuse","confusion","confused"],"correct_index":3}'::jsonb),
('chapter-69','vocabulary','immigrant','fill_blank','{"sentence_with_blank":"Simon left Norway for the United States. He is an ___.","accepted_answers":["immigrant"]}'::jsonb),
('chapter-69','vocabulary','forest','fill_blank','{"sentence_with_blank":"He buys a big ___ and starts cutting trees for wood.","accepted_answers":["forest"]}'::jsonb),
('chapter-69','vocabulary','thirsty','fill_blank','{"sentence_with_blank":"The work is hard and the men are hot and ___.","accepted_answers":["thirsty"]}'::jsonb),
('chapter-69','vocabulary','rich','fill_blank','{"sentence_with_blank":"His business does well, so Simon becomes very ___.","accepted_answers":["rich"]}'::jsonb),
('chapter-69','vocabulary','fountain','fill_blank','{"sentence_with_blank":"The city built twenty drinking ___ with his money.","accepted_answers":["fountain"]}'::jsonb),
('chapter-69','grammar','Simple present for life stories','multiple_choice','{"prompt":"Simon ___ Norway when he is seventeen.","options":["leave","leaving","is leave","leaves"],"correct_index":3}'::jsonb),
('chapter-69','grammar','Comparative with more','multiple_choice','{"prompt":"He works hard because he wants to make ___ money.","options":["many","more","most","much"],"correct_index":1}'::jsonb),
('chapter-127','vocabulary','hole','fill_blank','{"sentence_with_blank":"Dick sees a small round ___ in the middle of the street.","accepted_answers":["hole"]}'::jsonb),
('chapter-127','vocabulary','weed','fill_blank','{"sentence_with_blank":"Before planting flowers, Dick pulls every ___ out of the soil.","accepted_answers":["weed"]}'::jsonb),
('chapter-127','vocabulary','wish','fill_blank','{"sentence_with_blank":"The leprechaun grants him one ___, and he asks for a park.","accepted_answers":["wish"]}'::jsonb),
('chapter-127','vocabulary','newspaper','fill_blank','{"sentence_with_blank":"Dick writes his stories for a Portland ___.","accepted_answers":["newspaper"]}'::jsonb),
('chapter-127','grammar','Superlative with the -est','multiple_choice','{"prompt":"Mill Ends Park is ___ park in the world.","options":["smallest","the smallest","the most small","more small"],"correct_index":1}'::jsonb),
('chapter-127','grammar','Verbs of perception: look, see, sound','multiple_choice','{"prompt":"Every day he ___ out his window and sees the street.","options":["sees at","watches at","looks","looking"],"correct_index":2}'::jsonb),
('chapter-243','vocabulary','sculpture','fill_blank','{"sentence_with_blank":"The umbrella man is not a real person; he is a bronze ___.","accepted_answers":["sculpture"]}'::jsonb),
('chapter-243','vocabulary','bronze','fill_blank','{"sentence_with_blank":"The statue is made of ___, a heavy brown metal.","accepted_answers":["bronze"]}'::jsonb),
('chapter-243','vocabulary','artist','fill_blank','{"sentence_with_blank":"John Seward Johnson is the ___ who made the statue.","accepted_answers":["artist"]}'::jsonb),
('chapter-243','vocabulary','tourist','fill_blank','{"sentence_with_blank":"Some people say only a ___ carries an umbrella in Portland.","accepted_answers":["tourist"]}'::jsonb),
('chapter-243','grammar','Passive with was made / was built','multiple_choice','{"prompt":"The sculpture ___ in 1983.","options":["made","is make","was made","was make"],"correct_index":2}'::jsonb),
('chapter-243','grammar','Measurements: weighs, is ... tall','multiple_choice','{"prompt":"The statue ___ 460 pounds.","options":["is weigh","weight","has weight of","weighs"],"correct_index":3}'::jsonb),
('chapter-248','vocabulary','flood','fill_blank','{"sentence_with_blank":"The river broke through the wall and a terrible ___ covered the city.","accepted_answers":["flood"]}'::jsonb),
('chapter-248','vocabulary','destroy','fill_blank','{"sentence_with_blank":"The water was strong enough to ___ many buildings completely.","accepted_answers":["destroy"]}'::jsonb),
('chapter-248','vocabulary','separate','fill_blank','{"sentence_with_blank":"Only a wall of dirt was there to ___ the city from the river.","accepted_answers":["separate"]}'::jsonb),
('chapter-248','vocabulary','material','fill_blank','{"sentence_with_blank":"They built quickly and used cheap ___ that was not strong.","accepted_answers":["material"]}'::jsonb),
('chapter-248','vocabulary','company','fill_blank','{"sentence_with_blank":"A shipbuilding ___ needed workers, so it built houses for them.","accepted_answers":["company"]}'::jsonb),
('chapter-248','grammar','Past simple for finished events','multiple_choice','{"prompt":"On May 30, 1948, the dirt wall ___.","options":["broke","is broken","break","breaks"],"correct_index":0}'::jsonb),
('chapter-248','grammar','However for contrast','multiple_choice','{"prompt":"They said it was safe. ___, the wall was weak.","options":["However","Although of","So that","Because"],"correct_index":0}'::jsonb),
('chapter-253','vocabulary','nickname','fill_blank','{"sentence_with_blank":"\"Bridgetown\" is a ___ for Portland.","accepted_answers":["nickname"]}'::jsonb),
('chapter-253','vocabulary','deck','fill_blank','{"sentence_with_blank":"The Fremont Bridge has two levels; each level is called a ___.","accepted_answers":["deck"]}'::jsonb),
('chapter-253','vocabulary','concrete','fill_blank','{"sentence_with_blank":"The Burnside Bridge is made of ___, so it is very heavy.","accepted_answers":["concrete"]}'::jsonb),
('chapter-253','vocabulary','vehicle','fill_blank','{"sentence_with_blank":"A car, a bus and a truck are each a kind of ___.","accepted_answers":["vehicle"]}'::jsonb),
('chapter-253','vocabulary','earthquake','fill_blank','{"sentence_with_blank":"Engineers rebuilt the bridge to make it safer in an ___.","accepted_answers":["earthquake"]}'::jsonb),
('chapter-253','grammar','Passive in the past: was built, was replaced','multiple_choice','{"prompt":"The Broadway Bridge ___ in 1913.","options":["was build","is built","was built","built"],"correct_index":2}'::jsonb),
('chapter-253','grammar','Superlatives: the oldest, the busiest, the longest','multiple_choice','{"prompt":"The Marquam Bridge is ___ bridge in the state.","options":["the most busy","busiest","the busiest","more busy"],"correct_index":2}'::jsonb)
)
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
select ki.id, e.type, e.payload, 'draft' from e
join u on u.external_id = e.ext
join public.knowledge_items ki on ki.content_unit_id = u.id and ki.kind = e.kind and ki.dedup_key = e.key
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;