-- Knowledge extraction, hand-authored to stand in for the AI step
-- content-import cannot run without a key. Shapes match _shared/content.ts.
-- origin: ai_generated for authored definitions/explanations/labels;
-- source_derived for example sentences quoted verbatim from the chapter.

with u as (
  select cu.id, cu.external_id from public.content_units cu
  join public.content_sources cs on cs.id = cu.source_id
  where cs.source_url = 'https://openoregon.pressbooks.pub/homeandschool/'
), i(ext, kind, key, data, origin, status) as (values
('chapter-5','topic','greetings','{"label":"greetings"}'::jsonb,'ai_generated','draft'),
('chapter-5','vocabulary','classmate','{"word":"classmate","definition":"a person who studies in the same class as you"}'::jsonb,'ai_generated','draft'),
('chapter-5','vocabulary','friend','{"word":"friend","definition":"a person you know well and like"}'::jsonb,'ai_generated','draft'),
('chapter-5','vocabulary','happy','{"word":"happy","definition":"feeling good and pleased"}'::jsonb,'ai_generated','draft'),
('chapter-5','grammar','Subject pronouns: he, she, they','{"point":"Subject pronouns: he, she, they","explanation":"Use ''he'' for a man, ''she'' for a woman, and ''they'' for two or more people: He is Matt. She is Niki. They are friends."}'::jsonb,'ai_generated','draft'),
('chapter-5','grammar','Asking How are you?','{"point":"Asking How are you?","explanation":"A common greeting question. The usual answer is ''I''m good, thanks'' followed by the same question back."}'::jsonb,'ai_generated','draft'),
('chapter-5','example','chapter-5-ex0','{"sentence":"They go to English class."}'::jsonb,'source_derived','validated'),
('chapter-5','example','chapter-5-ex1','{"sentence":"Her name is Niki."}'::jsonb,'source_derived','validated'),
('chapter-20','topic','computers','{"label":"computers"}'::jsonb,'ai_generated','draft'),
('chapter-20','vocabulary','monitor','{"word":"monitor","definition":"the screen of a computer, where you read"}'::jsonb,'ai_generated','draft'),
('chapter-20','vocabulary','keyboard','{"word":"keyboard","definition":"the part of a computer with keys, where you type"}'::jsonb,'ai_generated','draft'),
('chapter-20','vocabulary','headphones','{"word":"headphones","definition":"something you wear on your ears to listen without noise for others"}'::jsonb,'ai_generated','draft'),
('chapter-20','vocabulary','printer','{"word":"printer","definition":"a machine that puts words from a computer onto paper"}'::jsonb,'ai_generated','draft'),
('chapter-20','grammar','This is + noun','{"point":"This is + noun","explanation":"Use ''This is a ___'' to name an object near you: This is a monitor. This is a keyboard."}'::jsonb,'ai_generated','draft'),
('chapter-20','example','chapter-20-ex0','{"sentence":"She studies English on a computer."}'::jsonb,'source_derived','validated'),
('chapter-20','example','chapter-20-ex1','{"sentence":"Tom asks, \"Where is a printer?\""}'::jsonb,'source_derived','validated'),
('chapter-22','topic','food-shopping','{"label":"food-shopping"}'::jsonb,'ai_generated','draft'),
('chapter-22','vocabulary','garlic','{"word":"garlic","definition":"a strong-tasting vegetable used in cooking"}'::jsonb,'ai_generated','draft'),
('chapter-22','vocabulary','cabbage','{"word":"cabbage","definition":"a large round vegetable with thick green leaves"}'::jsonb,'ai_generated','draft'),
('chapter-22','vocabulary','rice','{"word":"rice","definition":"small white or brown grains cooked and eaten as food"}'::jsonb,'ai_generated','draft'),
('chapter-22','grammar','Simple present with he/she: verb + s','{"point":"Simple present with he/she: verb + s","explanation":"With he or she, add -s to the verb: He buys lemons. He cooks dinner."}'::jsonb,'ai_generated','draft'),
('chapter-22','example','chapter-22-ex0','{"sentence":"Wu goes home. He cooks dinner."}'::jsonb,'source_derived','validated'),
('chapter-22','example','chapter-22-ex1','{"sentence":"He buys cabbage."}'::jsonb,'source_derived','validated'),
('chapter-24','topic','family-and-health','{"label":"family-and-health"}'::jsonb,'ai_generated','draft'),
('chapter-24','vocabulary','married','{"word":"married","definition":"having a husband or a wife"}'::jsonb,'ai_generated','draft'),
('chapter-24','vocabulary','daughter','{"word":"daughter","definition":"someone''s female child"}'::jsonb,'ai_generated','draft'),
('chapter-24','vocabulary','nurse','{"word":"nurse","definition":"a person who cares for sick people, often with a doctor"}'::jsonb,'ai_generated','draft'),
('chapter-24','vocabulary','sick','{"word":"sick","definition":"not well, ill"}'::jsonb,'ai_generated','draft'),
('chapter-24','grammar','How many + plural noun','{"point":"How many + plural noun","explanation":"Use ''How many'' to ask about number with countable nouns: How many children do you have?"}'::jsonb,'ai_generated','draft'),
('chapter-24','grammar','Negative with don''t','{"point":"Negative with don''t","explanation":"Use don''t + verb to make a negative with I, you, we, they: They don''t have a son."}'::jsonb,'ai_generated','draft'),
('chapter-24','example','chapter-24-ex0','{"sentence":"They have two children. They have two daughters."}'::jsonb,'source_derived','validated'),
('chapter-24','example','chapter-24-ex1','{"sentence":"Omar is sick today."}'::jsonb,'source_derived','validated'),
('chapter-26','topic','home-and-apartment','{"label":"home-and-apartment"}'::jsonb,'ai_generated','draft'),
('chapter-26','vocabulary','apartment','{"word":"apartment","definition":"a home inside a larger building, with rooms on one floor"}'::jsonb,'ai_generated','draft'),
('chapter-26','vocabulary','husband','{"word":"husband","definition":"the man a woman is married to"}'::jsonb,'ai_generated','draft'),
('chapter-26','vocabulary','kitchen','{"word":"kitchen","definition":"the room where you cook food"}'::jsonb,'ai_generated','draft'),
('chapter-26','vocabulary','living room','{"word":"living room","definition":"the room where a family sits together and relaxes"}'::jsonb,'ai_generated','draft'),
('chapter-26','grammar','Prepositions of place: in','{"point":"Prepositions of place: in","explanation":"Use ''in'' for being inside a room or building: Chet is in the kitchen. They live in an apartment."}'::jsonb,'ai_generated','draft'),
('chapter-26','example','chapter-26-ex0','{"sentence":"Chet is in the kitchen. He cooks dinner."}'::jsonb,'source_derived','validated'),
('chapter-26','example','chapter-26-ex1','{"sentence":"They watch TV after dinner."}'::jsonb,'source_derived','validated'),
('chapter-28','topic','school-supplies','{"label":"school-supplies"}'::jsonb,'ai_generated','draft'),
('chapter-28','vocabulary','pencil','{"word":"pencil","definition":"a thin tool for writing that can be erased"}'::jsonb,'ai_generated','draft'),
('chapter-28','vocabulary','eraser','{"word":"eraser","definition":"a small object that removes pencil marks"}'::jsonb,'ai_generated','draft'),
('chapter-28','vocabulary','paperclip','{"word":"paperclip","definition":"a small bent wire that holds sheets of paper together"}'::jsonb,'ai_generated','draft'),
('chapter-28','grammar','Yes/no questions with Do you have...?','{"point":"Yes/no questions with Do you have...?","explanation":"Use ''Do you have + noun?'' to ask if someone possesses something. Answer: Yes, I do / No, I don''t."}'::jsonb,'ai_generated','draft'),
('chapter-28','example','chapter-28-ex0','{"sentence":"He asks his mother. \"Do you have a pencil?\""}'::jsonb,'source_derived','validated'),
('chapter-28','example','chapter-28-ex1','{"sentence":"Bob needs five things. He has four things."}'::jsonb,'source_derived','validated'),
('chapter-30','topic','market-and-produce','{"label":"market-and-produce"}'::jsonb,'ai_generated','draft'),
('chapter-30','vocabulary','market','{"word":"market","definition":"a place where people buy and sell food and other goods"}'::jsonb,'ai_generated','draft'),
('chapter-30','vocabulary','tomato','{"word":"tomato","definition":"a soft round red fruit eaten in salads and cooking"}'::jsonb,'ai_generated','draft'),
('chapter-30','vocabulary','mushroom','{"word":"mushroom","definition":"a small soft vegetable with a round top and short stem"}'::jsonb,'ai_generated','draft'),
('chapter-30','vocabulary','watermelon','{"word":"watermelon","definition":"a very large green fruit that is red and sweet inside"}'::jsonb,'ai_generated','draft'),
('chapter-30','vocabulary','pear','{"word":"pear","definition":"a sweet fruit that is narrow at the top and round at the bottom"}'::jsonb,'ai_generated','draft'),
('chapter-30','grammar','There is / There are','{"point":"There is / There are","explanation":"Use ''There is'' with one thing and ''There are'' with more than one: There is a watermelon. There are red tomatoes."}'::jsonb,'ai_generated','draft'),
('chapter-30','grammar','Adjectives before nouns','{"point":"Adjectives before nouns","explanation":"In English the colour or quality goes before the noun: red apples, green pepper, yellow corn."}'::jsonb,'ai_generated','draft'),
('chapter-30','example','chapter-30-ex0','{"sentence":"The market has many fruits and vegetables."}'::jsonb,'source_derived','validated'),
('chapter-30','example','chapter-30-ex1','{"sentence":"She buys a green pepper."}'::jsonb,'source_derived','validated'),
('chapter-246','topic','transport-and-routine','{"label":"transport-and-routine"}'::jsonb,'ai_generated','draft'),
('chapter-246','vocabulary','truck','{"word":"truck","definition":"a large road vehicle for carrying goods"}'::jsonb,'ai_generated','draft'),
('chapter-246','vocabulary','van','{"word":"van","definition":"a covered vehicle smaller than a truck, for carrying things"}'::jsonb,'ai_generated','draft'),
('chapter-246','vocabulary','job','{"word":"job","definition":"the work a person does to earn money"}'::jsonb,'ai_generated','draft'),
('chapter-246','grammar','Days of the week with on','{"point":"Days of the week with on","explanation":"Use ''on'' before a day: He has English class on Monday, Wednesday, and Friday."}'::jsonb,'ai_generated','draft'),
('chapter-246','grammar','Adverbs of frequency: sometimes, every day','{"point":"Adverbs of frequency: sometimes, every day","explanation":"These words say how often something happens: Sometimes he rides his bike. Every day, Hugo walks outside."}'::jsonb,'ai_generated','draft'),
('chapter-246','example','chapter-246-ex0','{"sentence":"He takes a bus to school."}'::jsonb,'source_derived','validated'),
('chapter-246','example','chapter-246-ex1','{"sentence":"Hugo has a job. He works on Tuesday, Thursday, and Saturday."}'::jsonb,'source_derived','validated'),
('chapter-34','topic','weather','{"label":"weather"}'::jsonb,'ai_generated','draft'),
('chapter-34','vocabulary','sunny','{"word":"sunny","definition":"with a lot of sun and no clouds"}'::jsonb,'ai_generated','draft'),
('chapter-34','vocabulary','snowy','{"word":"snowy","definition":"with snow falling or on the ground"}'::jsonb,'ai_generated','draft'),
('chapter-34','vocabulary','foggy','{"word":"foggy","definition":"with thick cloud near the ground, so you cannot see far"}'::jsonb,'ai_generated','draft'),
('chapter-34','vocabulary','scarf','{"word":"scarf","definition":"a piece of cloth worn around the neck to keep warm"}'::jsonb,'ai_generated','draft'),
('chapter-34','vocabulary','gloves','{"word":"gloves","definition":"coverings for the hands, worn when it is cold"}'::jsonb,'ai_generated','draft'),
('chapter-34','grammar','It is + weather adjective','{"point":"It is + weather adjective","explanation":"Describe weather with ''It is'': It''s cold and snowy. It is windy and foggy."}'::jsonb,'ai_generated','draft'),
('chapter-34','grammar','Asking How is the weather?','{"point":"Asking How is the weather?","explanation":"The standard question about weather. Answer with ''It is'' plus an adjective."}'::jsonb,'ai_generated','draft'),
('chapter-34','example','chapter-34-ex0','{"sentence":"\"It''s cold and snowy. I have my hat, my scarf, and my gloves.\""}'::jsonb,'source_derived','validated'),
('chapter-34','example','chapter-34-ex1','{"sentence":"She lives in Portland. The weather is beautiful today."}'::jsonb,'source_derived','validated'),
('chapter-32','topic','holidays-and-months','{"label":"holidays-and-months"}'::jsonb,'ai_generated','draft'),
('chapter-32','vocabulary','holiday','{"word":"holiday","definition":"a special day when people do not work and often celebrate"}'::jsonb,'ai_generated','draft'),
('chapter-32','vocabulary','celebrate','{"word":"celebrate","definition":"to do something special to mark an important day"}'::jsonb,'ai_generated','draft'),
('chapter-32','vocabulary','parade','{"word":"parade","definition":"a public march with music, often for a holiday"}'::jsonb,'ai_generated','draft'),
('chapter-32','vocabulary','costume','{"word":"costume","definition":"clothes worn to look like someone or something else"}'::jsonb,'ai_generated','draft'),
('chapter-32','grammar','Dates: months and ordinal position','{"point":"Dates: months and ordinal position","explanation":"Say the month with the day: Independence Day is July 4. Use ''in'' with a month alone: Mother''s Day is in May."}'::jsonb,'ai_generated','draft'),
('chapter-32','grammar','We + simple present for customs','{"point":"We + simple present for customs","explanation":"Use ''we'' with the simple present to describe what people generally do: We celebrate holidays in different ways."}'::jsonb,'ai_generated','draft'),
('chapter-32','example','chapter-32-ex0','{"sentence":"We have many holidays in the United States."}'::jsonb,'source_derived','validated'),
('chapter-32','example','chapter-32-ex1','{"sentence":"Children wear fun costumes, and they get candy."}'::jsonb,'source_derived','validated')
)
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
select u.id, i.kind, i.key, i.data, i.origin, i.status from i join u on u.external_id = i.ext
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, origin = excluded.origin, status = excluded.status;

with u as (
  select cu.id, cu.external_id from public.content_units cu
  join public.content_sources cs on cs.id = cu.source_id
  where cs.source_url = 'https://openoregon.pressbooks.pub/homeandschool/'
), e(ext, kind, key, type, payload) as (values
('chapter-5','vocabulary','classmate','fill_blank','{"sentence_with_blank":"Niki sits next to me in English class. She is my ___.","accepted_answers":["classmate"]}'::jsonb),
('chapter-5','vocabulary','friend','fill_blank','{"sentence_with_blank":"Matt and Niki like each other. They are ___.","accepted_answers":["friend"]}'::jsonb),
('chapter-5','vocabulary','happy','fill_blank','{"sentence_with_blank":"She is smiling because she is ___.","accepted_answers":["happy"]}'::jsonb),
('chapter-5','grammar','Subject pronouns: he, she, they','multiple_choice','{"prompt":"Niki is a woman. ___ is a student.","options":["It","He","She","They"],"correct_index":2}'::jsonb),
('chapter-5','grammar','Asking How are you?','multiple_choice','{"prompt":"\"How are you?\" — \"___\"","options":["I am twenty.","I''m good, thanks.","Yes, I am.","My name is Tom."],"correct_index":1}'::jsonb),
('chapter-20','vocabulary','monitor','fill_blank','{"sentence_with_blank":"She reads the words on the ___.","accepted_answers":["monitor"]}'::jsonb),
('chapter-20','vocabulary','keyboard','fill_blank','{"sentence_with_blank":"He types his name on the ___.","accepted_answers":["keyboard"]}'::jsonb),
('chapter-20','vocabulary','headphones','fill_blank','{"sentence_with_blank":"The classroom is quiet, so Minako listens with ___.","accepted_answers":["headphones"]}'::jsonb),
('chapter-20','vocabulary','printer','fill_blank','{"sentence_with_blank":"Tom needs paper copies, so he looks for the ___.","accepted_answers":["printer"]}'::jsonb),
('chapter-20','grammar','This is + noun','multiple_choice','{"prompt":"Point to the mouse and name it:","options":["This is mouse.","This is a mouse.","Is this a mouse.","This a mouse."],"correct_index":1}'::jsonb),
('chapter-22','vocabulary','garlic','fill_blank','{"sentence_with_blank":"He puts ___ in the soup to give it a strong taste.","accepted_answers":["garlic"]}'::jsonb),
('chapter-22','vocabulary','cabbage','fill_blank','{"sentence_with_blank":"She buys a big green ___ for the salad.","accepted_answers":["cabbage"]}'::jsonb),
('chapter-22','vocabulary','rice','fill_blank','{"sentence_with_blank":"They eat fish with ___ for dinner.","accepted_answers":["rice"]}'::jsonb),
('chapter-22','grammar','Simple present with he/she: verb + s','multiple_choice','{"prompt":"Wu ___ dinner every evening.","options":["cooks","cook","is cook","cooking"],"correct_index":0}'::jsonb),
('chapter-24','vocabulary','married','fill_blank','{"sentence_with_blank":"Omar and Rosa are ___. They have two children.","accepted_answers":["married"]}'::jsonb),
('chapter-24','vocabulary','daughter','fill_blank','{"sentence_with_blank":"Their ___ is four years old. She is a girl.","accepted_answers":["daughter"]}'::jsonb),
('chapter-24','vocabulary','nurse','fill_blank','{"sentence_with_blank":"The ___ asks how many children they have.","accepted_answers":["nurse"]}'::jsonb),
('chapter-24','vocabulary','sick','fill_blank','{"sentence_with_blank":"Omar feels bad today. He is ___.","accepted_answers":["sick"]}'::jsonb),
('chapter-24','grammar','How many + plural noun','multiple_choice','{"prompt":"___ children do you have?","options":["How much","How many","How old","How long"],"correct_index":1}'::jsonb),
('chapter-24','grammar','Negative with don''t','multiple_choice','{"prompt":"They have two daughters. They ___ a son.","options":["doesn''t have","don''t have","not have","have not"],"correct_index":1}'::jsonb),
('chapter-26','vocabulary','apartment','fill_blank','{"sentence_with_blank":"They do not have a house. They live in an ___.","accepted_answers":["apartment"]}'::jsonb),
('chapter-26','vocabulary','husband','fill_blank','{"sentence_with_blank":"Sunee is married to Chet. He is her ___.","accepted_answers":["husband"]}'::jsonb),
('chapter-26','vocabulary','kitchen','fill_blank','{"sentence_with_blank":"Chet is cooking dinner in the ___.","accepted_answers":["kitchen"]}'::jsonb),
('chapter-26','vocabulary','living room','fill_blank','{"sentence_with_blank":"After dinner the family watches TV in the ___.","accepted_answers":["living room"]}'::jsonb),
('chapter-26','grammar','Prepositions of place: in','multiple_choice','{"prompt":"Sunee studies English ___ the living room.","options":["on","to","in","at"],"correct_index":2}'::jsonb),
('chapter-28','vocabulary','pencil','fill_blank','{"sentence_with_blank":"He writes with a ___ so he can erase his mistakes.","accepted_answers":["pencil"]}'::jsonb),
('chapter-28','vocabulary','eraser','fill_blank','{"sentence_with_blank":"She made a mistake, so she used an ___.","accepted_answers":["eraser"]}'::jsonb),
('chapter-28','vocabulary','paperclip','fill_blank','{"sentence_with_blank":"He holds the two pages together with a ___.","accepted_answers":["paperclip"]}'::jsonb),
('chapter-28','grammar','Yes/no questions with Do you have...?','multiple_choice','{"prompt":"___ you have a pencil?","options":["Does","Are","Is","Do"],"correct_index":3}'::jsonb),
('chapter-30','vocabulary','market','fill_blank','{"sentence_with_blank":"Ann buys fruit and vegetables at the ___.","accepted_answers":["market"]}'::jsonb),
('chapter-30','vocabulary','tomato','fill_blank','{"sentence_with_blank":"She puts a red ___ in her salad.","accepted_answers":["tomato"]}'::jsonb),
('chapter-30','vocabulary','mushroom','fill_blank','{"sentence_with_blank":"He cooks a brown ___ with the onions.","accepted_answers":["mushroom"]}'::jsonb),
('chapter-30','vocabulary','watermelon','fill_blank','{"sentence_with_blank":"The ___ is green outside and red inside.","accepted_answers":["watermelon"]}'::jsonb),
('chapter-30','vocabulary','pear','fill_blank','{"sentence_with_blank":"They have no apples today, but they have a ___.","accepted_answers":["pear"]}'::jsonb),
('chapter-30','grammar','There is / There are','multiple_choice','{"prompt":"___ many fruits and vegetables at the market.","options":["There is","It has","Have","There are"],"correct_index":3}'::jsonb),
('chapter-30','grammar','Adjectives before nouns','multiple_choice','{"prompt":"Ann buys a ___.","options":["green of pepper","green pepper","pepper of green","pepper green"],"correct_index":1}'::jsonb),
('chapter-246','vocabulary','truck','fill_blank','{"sentence_with_blank":"At work Hugo drives a big ___ full of boxes.","accepted_answers":["truck"]}'::jsonb),
('chapter-246','vocabulary','van','fill_blank','{"sentence_with_blank":"Sometimes he drives a smaller ___ instead of the truck.","accepted_answers":["van"]}'::jsonb),
('chapter-246','vocabulary','job','fill_blank','{"sentence_with_blank":"Hugo studies on Monday and goes to his ___ on Tuesday.","accepted_answers":["job"]}'::jsonb),
('chapter-246','grammar','Days of the week with on','multiple_choice','{"prompt":"He works ___ Tuesday.","options":["at","on","in","to"],"correct_index":1}'::jsonb),
('chapter-246','grammar','Adverbs of frequency: sometimes, every day','multiple_choice','{"prompt":"___ he rides his bike, but usually he takes the bus.","options":["Never","Every day","Sometimes","Always"],"correct_index":2}'::jsonb),
('chapter-34','vocabulary','sunny','fill_blank','{"sentence_with_blank":"There are no clouds today. It is warm and ___.","accepted_answers":["sunny"]}'::jsonb),
('chapter-34','vocabulary','snowy','fill_blank','{"sentence_with_blank":"In Toronto it is cold and ___ in winter.","accepted_answers":["snowy"]}'::jsonb),
('chapter-34','vocabulary','foggy','fill_blank','{"sentence_with_blank":"It is so ___ at the beach that Susan cannot see the ocean.","accepted_answers":["foggy"]}'::jsonb),
('chapter-34','vocabulary','scarf','fill_blank','{"sentence_with_blank":"When it is cold she wears a hat and a ___.","accepted_answers":["scarf"]}'::jsonb),
('chapter-34','vocabulary','gloves','fill_blank','{"sentence_with_blank":"My hands are cold. Where are my ___?","accepted_answers":["gloves"]}'::jsonb),
('chapter-34','grammar','It is + weather adjective','multiple_choice','{"prompt":"How is the weather? ___ cold and rainy.","options":["Is","There''s","It''s","He''s"],"correct_index":2}'::jsonb),
('chapter-34','grammar','Asking How is the weather?','multiple_choice','{"prompt":"Which question asks about the weather?","options":["How much is the weather?","Where is the weather?","What weather do you have it?","How is the weather today?"],"correct_index":3}'::jsonb),
('chapter-32','vocabulary','holiday','fill_blank','{"sentence_with_blank":"Independence Day is a ___ in the United States.","accepted_answers":["holiday"]}'::jsonb),
('chapter-32','vocabulary','celebrate','fill_blank','{"sentence_with_blank":"People ___ New Year''s Eve with parties.","accepted_answers":["celebrate"]}'::jsonb),
('chapter-32','vocabulary','parade','fill_blank','{"sentence_with_blank":"On July 4 there are flags, fireworks and a ___.","accepted_answers":["parade"]}'::jsonb),
('chapter-32','vocabulary','costume','fill_blank','{"sentence_with_blank":"At Halloween children wear a fun ___ and get candy.","accepted_answers":["costume"]}'::jsonb),
('chapter-32','grammar','Dates: months and ordinal position','multiple_choice','{"prompt":"Mother''s Day is ___ May.","options":["in","at","of","on"],"correct_index":0}'::jsonb),
('chapter-32','grammar','We + simple present for customs','multiple_choice','{"prompt":"___ many holidays in the United States.","options":["We have","We are have","We having","We has"],"correct_index":0}'::jsonb)
)
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
select ki.id, e.type, e.payload, 'draft' from e
join u on u.external_id = e.ext
join public.knowledge_items ki on ki.content_unit_id = u.id and ki.kind = e.kind and ki.dedup_key = e.key
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;