-- ===== When the flight is cancelled (B2) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-flight-cancelled', 'chapter', 'When the flight is cancelled', 12, jsonb_build_array(
  jsonb_build_object('type', 'paragraph', 'text', 'Few things test a traveller''s patience like the word CANCELLED appearing beside a flight number an hour before departure. What matters at that point is knowing what you are owed, because airlines rarely volunteer it.'),
  jsonb_build_object('type', 'paragraph', 'text', 'Under European rules, passengers whose flights are cancelled at short notice are usually entitled to compensation as well as a refund or a seat on a later flight. The two are separate: accepting a replacement seat does not cancel the right to be compensated.'),
  jsonb_build_object('type', 'paragraph', 'text', 'The airline is also obliged to look after passengers while they wait. If the delay stretches overnight, that normally includes a hotel room and transport to it. Staff at the gate will not always mention this, and it is worth asking directly.'),
  jsonb_build_object('type', 'paragraph', 'text', 'There are exceptions. If the cancellation was caused by something genuinely outside the airline''s control, such as severe weather or a closed airspace, compensation may not be payable, although the refund still is. Airlines have been known to describe ordinary technical faults as extraordinary circumstances, and that claim does not always survive scrutiny.'),
  jsonb_build_object('type', 'paragraph', 'text', 'Practical advice from people who claim successfully tends to be the same. Keep the boarding pass. Photograph the departure board showing the cancellation. Ask the airline, in writing, for the reason. A claim supported by evidence is far harder to refuse than one based on memory.'),
  jsonb_build_object('type', 'paragraph', 'text', 'None of this makes a ruined journey pleasant. It does, however, shift the balance a little towards the passenger, which is presumably why the rules were written in the first place.')
), now(), 251, 'parsed', 'B2'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;

insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'topic', 'travel-and-accommodation', jsonb_build_object('label', 'travel-and-accommodation'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'vocabulary', 'entitled', jsonb_build_object('word', 'entitled', 'definition', 'having the legal right to receive something'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'vocabulary' and ki.dedup_key = 'entitled'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'Passengers whose flights are cancelled late are often ___ to money as well as a refund.', 'accepted_answers', jsonb_build_array('entitled')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'vocabulary', 'compensation', jsonb_build_object('word', 'compensation', 'definition', 'money paid to someone because something went wrong'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'vocabulary' and ki.dedup_key = 'compensation'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'Beyond the refund, the airline may owe ___ for the disruption.', 'accepted_answers', jsonb_build_array('compensation')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'vocabulary', 'refund', jsonb_build_object('word', 'refund', 'definition', 'money returned to you for something you paid for but did not receive'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'vocabulary' and ki.dedup_key = 'refund'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'If you choose not to travel at all, you can ask for a full ___.', 'accepted_answers', jsonb_build_array('refund')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'vocabulary', 'obliged', jsonb_build_object('word', 'obliged', 'definition', 'required by law or rules to do something'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'vocabulary' and ki.dedup_key = 'obliged'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'While passengers wait, the airline is ___ to provide meals and a room.', 'accepted_answers', jsonb_build_array('obliged')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'vocabulary', 'scrutiny', jsonb_build_object('word', 'scrutiny', 'definition', 'careful and critical examination'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'vocabulary' and ki.dedup_key = 'scrutiny'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'The airline''s excuse did not survive close ___ by the regulator.', 'accepted_answers', jsonb_build_array('scrutiny')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'grammar', 'Passive with be + past participle for rules', jsonb_build_object('point', 'Passive with be + past participle for rules', 'explanation', 'Rules and procedures are usually stated in the passive, because the actor is obvious or unimportant: Compensation may not be payable. The rules were written to protect passengers.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'grammar' and ki.dedup_key = 'Passive with be + past participle for rules'), 'multiple_choice', jsonb_build_object('prompt', 'Compensation ___ if the cause was severe weather.', 'options', jsonb_build_array('not may be payable', 'may not payable', 'may be not pay', 'may not be payable'), 'correct_index', 3::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'grammar', 'Concession with although and however', jsonb_build_object('point', 'Concession with although and however', 'explanation', 'Use ''although'' inside a sentence and ''however'' between sentences to concede a point: Compensation may not apply, although the refund still does.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'grammar' and ki.dedup_key = 'Concession with although and however'), 'multiple_choice', jsonb_build_object('prompt', 'Compensation may not apply, ___ the refund still does.', 'options', jsonb_build_array('despite', 'although', 'however', 'in spite'), 'correct_index', 1::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'grammar', 'Reduced relative clauses', jsonb_build_object('point', 'Reduced relative clauses', 'explanation', 'A relative clause can drop ''who/which is'': passengers whose flights are cancelled, a claim supported by evidence.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled') and ki.kind = 'grammar' and ki.dedup_key = 'Reduced relative clauses'), 'multiple_choice', jsonb_build_object('prompt', 'A claim ___ by evidence is harder to refuse.', 'options', jsonb_build_array('supported', 'supporting', 'which supporting', 'it supported'), 'correct_index', 0::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'example', 'authored-flight-cancelled-ex0', jsonb_build_object('sentence', 'Accepting a replacement seat does not cancel the right to be compensated.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), 'example', 'authored-flight-cancelled-ex1', jsonb_build_object('sentence', 'A claim supported by evidence is far harder to refuse.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), (select id from public.topics where slug = 'travel-and-accommodation'))
on conflict do nothing;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-flight-cancelled'), (select id from public.topics where slug = 'transport-and-directions'))
on conflict do nothing;
