-- ===== Why we misjudge our own plans (C1) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-misjudging-plans', 'chapter', 'Why we misjudge our own plans', 14, jsonb_build_array(
  jsonb_build_object('type', 'paragraph', 'text', 'Ask a group of people how long a piece of work will take them and the answers will cluster optimistically, often absurdly so. Ask the same people how long it would take someone else, and the estimates lengthen considerably. The asymmetry is well documented, and it is not obviously a failure of intelligence.'),
  jsonb_build_object('type', 'paragraph', 'text', 'One explanation is that we plan from the inside. Imagining a task, we rehearse the smooth version of it: the version without the interruption, the missing file, the colleague who does not reply. Nothing in that mental rehearsal is dishonest. It is simply incomplete in a systematic direction.'),
  jsonb_build_object('type', 'paragraph', 'text', 'What makes the bias stubborn is that experience does not readily correct it. Someone who has missed the last five deadlines will frequently produce a sixth estimate no more generous than the others, on the grounds that this time the circumstances are different. Occasionally they are.'),
  jsonb_build_object('type', 'paragraph', 'text', 'The remedies that appear to work are unglamorous. Rather than reasoning about the task in front of you, look at how long comparable tasks actually took, however unrepresentative each of them felt at the time. Where records exist, they tend to beat intuition.'),
  jsonb_build_object('type', 'paragraph', 'text', 'It would be convenient to conclude that we should simply pad every estimate. That advice founders quickly, since padded deadlines are themselves treated as soft and expand to fill the space allowed. The more defensible conclusion is narrower: distrust the confidence, not the plan.')
), now(), 234, 'parsed', 'C1'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;

insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'topic', 'feelings-and-opinions', jsonb_build_object('label', 'feelings-and-opinions'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'vocabulary', 'asymmetry', jsonb_build_object('word', 'asymmetry', 'definition', 'a difference between two sides of something that should match'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'vocabulary' and ki.dedup_key = 'asymmetry'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'The ___ is striking: we are generous about others and harsh about ourselves.', 'accepted_answers', jsonb_build_array('asymmetry')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'vocabulary', 'stubborn', jsonb_build_object('word', 'stubborn', 'definition', 'difficult to change or remove despite effort'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'vocabulary' and ki.dedup_key = 'stubborn'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'The bias is ___ because failing repeatedly does not seem to cure it.', 'accepted_answers', jsonb_build_array('stubborn')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'vocabulary', 'unglamorous', jsonb_build_object('word', 'unglamorous', 'definition', 'dull and lacking excitement, though possibly effective'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'vocabulary' and ki.dedup_key = 'unglamorous'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'The remedies that work are ___ - keep records and consult them.', 'accepted_answers', jsonb_build_array('unglamorous')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'vocabulary', 'founder', jsonb_build_object('word', 'founder', 'definition', 'to fail completely, especially after a promising start'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'vocabulary' and ki.dedup_key = 'founder'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'The simple advice to pad every estimate tends to ___ once people learn to expect the padding.', 'accepted_answers', jsonb_build_array('founder')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'vocabulary', 'defensible', jsonb_build_object('word', 'defensible', 'definition', 'able to be justified with reasons'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'vocabulary' and ki.dedup_key = 'defensible'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'A narrower claim is more ___ than a sweeping one.', 'accepted_answers', jsonb_build_array('defensible')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'grammar', 'Hedging with tend to, appear to, may well', jsonb_build_object('point', 'Hedging with tend to, appear to, may well', 'explanation', 'Careful writing softens claims rather than asserting them flatly: the remedies that appear to work; records tend to beat intuition.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'grammar' and ki.dedup_key = 'Hedging with tend to, appear to, may well'), 'multiple_choice', jsonb_build_object('prompt', 'Written records ___ beat intuition, though not always.', 'options', jsonb_build_array('tend for', 'tends to', 'tend to', 'are tending'), 'correct_index', 2::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'grammar', 'Fronting a concessive clause with however + adjective', jsonb_build_object('point', 'Fronting a concessive clause with however + adjective', 'explanation', '''However'' plus an adjective concedes a point before the main clause: however unrepresentative each of them felt at the time.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'grammar' and ki.dedup_key = 'Fronting a concessive clause with however + adjective'), 'multiple_choice', jsonb_build_object('prompt', 'Look at comparable tasks, ___ unusual each one felt.', 'options', jsonb_build_array('although', 'whatever', 'despite', 'however'), 'correct_index', 3::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'grammar', 'Inversion after negative adverbials', jsonb_build_object('point', 'Inversion after negative adverbials', 'explanation', 'After a fronted negative expression the subject and auxiliary swap: Rarely does experience correct the bias on its own.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans') and ki.kind = 'grammar' and ki.dedup_key = 'Inversion after negative adverbials'), 'multiple_choice', jsonb_build_object('prompt', 'Rarely ___ experience correct the bias on its own.', 'options', jsonb_build_array('is', 'it does', 'does', 'do'), 'correct_index', 2::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'example', 'authored-misjudging-plans-ex0', jsonb_build_object('sentence', 'We plan from the inside, rehearsing the smooth version of the task.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), 'example', 'authored-misjudging-plans-ex1', jsonb_build_object('sentence', 'Distrust the confidence, not the plan.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-misjudging-plans'), (select id from public.topics where slug = 'feelings-and-opinions'))
on conflict do nothing;
