-- ===== The cost of preserving a city (C1) =====
insert into public.content_units (source_id, external_id, kind, title, position, parsed_blocks, parsed_at, word_count, status, cefr_level)
values ((select id from public.content_sources where source_url = 'yuny://authored/en/v1'), 'authored-preserving-a-city', 'chapter', 'The cost of preserving a city', 15, jsonb_build_array(
  jsonb_build_object('type', 'paragraph', 'text', 'Every city that has decided to protect its old buildings has, in the same decision, decided something about who gets to live there. That second consequence is rarely stated as plainly as the first.'),
  jsonb_build_object('type', 'paragraph', 'text', 'The case for conservation is easy to make and largely sound. Streets that survive intact are pleasant, legible and unrepeatable; once demolished, they cannot be reconstructed in any meaningful sense. Few people who have watched an unloved district be flattened would argue otherwise.'),
  jsonb_build_object('type', 'paragraph', 'text', 'What is less often acknowledged is the arithmetic. Height limits, facade rules and heritage designations all constrain the number of homes that can be built in precisely the places where demand is highest. Constrained supply meeting undiminished demand produces the predictable result, and the result is not evenly distributed.'),
  jsonb_build_object('type', 'paragraph', 'text', 'This is not an argument for demolition. It is an argument for honesty about trade-offs. A city may reasonably decide that a particular street is worth more than the flats that could replace it, but the decision costs something, and somebody pays it - usually people who are not in the room when it is taken.'),
  jsonb_build_object('type', 'paragraph', 'text', 'Where the debate goes wrong is in pretending the choice is between civilisation and greed. It is more often between two goods that cannot both be maximised, which is a harder argument to have and a duller headline to write.')
), now(), 222, 'parsed', 'C1'::public.cefr_level)
on conflict (source_id, external_id) do update set parsed_blocks = excluded.parsed_blocks, word_count = excluded.word_count, cefr_level = excluded.cefr_level, title = excluded.title;

insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'topic', 'history-and-society', jsonb_build_object('label', 'history-and-society'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'vocabulary', 'heritage', jsonb_build_object('word', 'heritage', 'definition', 'buildings and traditions from the past that a society tries to keep'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'vocabulary' and ki.dedup_key = 'heritage'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'A ___ designation protects the building but also limits what can replace it.', 'accepted_answers', jsonb_build_array('heritage')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'vocabulary', 'constrain', jsonb_build_object('word', 'constrain', 'definition', 'to limit or restrict what is possible'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'vocabulary' and ki.dedup_key = 'constrain'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'Height limits ___ how many homes a district can hold.', 'accepted_answers', jsonb_build_array('constrain')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'vocabulary', 'trade-off', jsonb_build_object('word', 'trade-off', 'definition', 'a situation where you accept less of one good thing to get more of another'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'vocabulary' and ki.dedup_key = 'trade-off'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'Honesty about the ___ matters more than pretending there is no cost.', 'accepted_answers', jsonb_build_array('trade-off')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'vocabulary', 'legible', jsonb_build_object('word', 'legible', 'definition', 'easy to read or, of a place, easy to understand and navigate'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'vocabulary' and ki.dedup_key = 'legible'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'An old street grid is often more ___ to a visitor than a modern one.', 'accepted_answers', jsonb_build_array('legible')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'vocabulary', 'acknowledge', jsonb_build_object('word', 'acknowledge', 'definition', 'to accept or admit that something is true'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'vocabulary' and ki.dedup_key = 'acknowledge'), 'fill_blank', jsonb_build_object('sentence_with_blank', 'Supporters of conservation rarely ___ the arithmetic of restricted supply.', 'accepted_answers', jsonb_build_array('acknowledge')), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'grammar', 'Cleft sentences with what', jsonb_build_object('point', 'Cleft sentences with what', 'explanation', 'A what-cleft moves the important part to the end for emphasis: What is less often acknowledged is the arithmetic.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'grammar' and ki.dedup_key = 'Cleft sentences with what'), 'multiple_choice', jsonb_build_object('prompt', '___ is less often acknowledged is the cost.', 'options', jsonb_build_array('What', 'It', 'That', 'Which'), 'correct_index', 0::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'grammar', 'Nominalisation in formal register', jsonb_build_object('point', 'Nominalisation in formal register', 'explanation', 'Formal writing turns verbs into nouns: supply is constrained becomes constrained supply; they decided becomes the decision.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'grammar' and ki.dedup_key = 'Nominalisation in formal register'), 'multiple_choice', jsonb_build_object('prompt', 'Choose the more formal phrasing.', 'options', jsonb_build_array('Constrained supply meeting undiminished demand produces a predictable result.', 'Supply being constrained, demand not going down, result is predictable.', 'The supply constrained and the demand undiminished produce predictable.', 'Because supply is constrained and demand did not go down, you get what you expect.'), 'correct_index', 0::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'grammar', 'Contrast with whereas and while', jsonb_build_object('point', 'Contrast with whereas and while', 'explanation', '''Whereas'' and clause-initial ''while'' set two statements against each other: While the case for conservation is sound, its costs are unevenly shared.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.generated_exercises (knowledge_item_id, type, payload, status)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city') and ki.kind = 'grammar' and ki.dedup_key = 'Contrast with whereas and while'), 'multiple_choice', jsonb_build_object('prompt', '___ the case for conservation is sound, its costs fall unevenly.', 'options', jsonb_build_array('Even', 'Despite', 'While', 'However'), 'correct_index', 2::int), 'draft')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'example', 'authored-preserving-a-city-ex0', jsonb_build_object('sentence', 'The decision costs something, and somebody pays it.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), 'example', 'authored-preserving-a-city-ex1', jsonb_build_object('sentence', 'It is more often between two goods that cannot both be maximised.'), 'ai_generated', 'draft')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), (select id from public.topics where slug = 'history-and-society'))
on conflict do nothing;
insert into public.content_unit_topics (content_unit_id, topic_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-preserving-a-city'), (select id from public.topics where slug = 'city-and-places'))
on conflict do nothing;
