/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "media",
  content: [
    "./app/**/*.{ts,tsx}",
    "./features/**/*.{ts,tsx}",
    "./shared/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#7B6BD6",
        "primary-dark": "#9B8FE3",
        "primary-soft": "#EFECFB",
        "primary-soft-dark": "#2B2547",
        accent: "#FFD764",
        "accent-soft": "#FFF6DC",
        "accent-soft-dark": "#3A3320",
        info: "#6BC0EC",
        success: "#4A9B6E",
        "success-dark": "#5FB584",
        warning: "#E8A54B",
        danger: "#D96A6A",
        "danger-dark": "#E58585",
        background: "#FAF7F2",
        "background-dark": "#17142A",
        surface: "#FFFFFF",
        "surface-dark": "#221E3B",
        "surface-alt": "#F3EFE8",
        "surface-alt-dark": "#2B2547",
        border: "#E6E0D6",
        "border-dark": "#332D52",
        text: "#2A2440",
        "text-dark": "#F2EFF8",
        "text-muted": "#7A7391",
        "text-muted-dark": "#A9A2C4",
        "text-inverse": "#FFFFFF",
        "text-inverse-dark": "#17142A",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        pill: "999px",
      },
      fontSize: {
        display: ["32px", { lineHeight: "40px", fontWeight: "700" }],
        title: ["24px", { lineHeight: "32px", fontWeight: "700" }],
        heading: ["18px", { lineHeight: "26px", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
