insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'book a table', '{"word":"book a table","definition":"to call or write to a restaurant and ask them to keep a table free for you","example":"In the morning she calls the restaurant to book a table."}'::jsonb, 'ai_generated', 'validated', 'LO-2')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'book a table'), 'multiple_choice', '{"prompt":"Maya called the restaurant and asked them to keep two places for seven o''clock. What did she do?","options":["She ordered the food.","She paid the bill in cash.","She booked a table.","She asked the waiter to recommend a dish."],"correct_index":2}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'waiter', '{"word":"waiter","definition":"the person in a restaurant who takes your order and brings your food to the table; in American English people often say server","example":"A waiter meets them at the door."}'::jsonb, 'ai_generated', 'validated', 'LO-2')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'waiter'), 'fill_blank', '{"sentence_with_blank":"A young man brings the menu and takes their order, so he is their ___.","accepted_answers":["waiter","server"]}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'order', '{"word":"order","definition":"to tell the waiter what food or drink you want; also the food you asked for","example":"Tom orders the soup and then the chicken with rice."}'::jsonb, 'ai_generated', 'validated', 'LO-2')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'order'), 'multiple_choice', '{"prompt":"Maya told the waiter that she wanted the daily special. What did she do?","options":["She booked a table.","She asked for the bill.","She left a tip for the waiter.","She ordered her food."],"correct_index":3}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'order'), 'fill_blank', '{"sentence_with_blank":"The waiter writes in his little book and takes the ___ to the kitchen.","accepted_answers":["order"]}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'recommend', '{"word":"recommend","definition":"to tell someone which thing you think is good, so they can choose it","example":"He asks the waiter to recommend something."}'::jsonb, 'ai_generated', 'validated', 'LO-2')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'recommend'), 'multiple_choice', '{"prompt":"Tom does not know this restaurant, so he asks the waiter which dish is best. What does Tom want the waiter to do?","options":["to book a table for them","to recommend a dish","to bring the bill","to split the bill with him"],"correct_index":1}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'allergic', '{"word":"allergic","definition":"made ill by one kind of food, so you must not eat it","example":"Tom is allergic to fish, so he asks about the soup first."}'::jsonb, 'ai_generated', 'validated', 'LO-2')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'allergic'), 'fill_blank', '{"sentence_with_blank":"Fish makes Tom ill, so he tells the waiter that he is ___ to fish.","accepted_answers":["allergic"]}'::jsonb, 'validated', 'LO-2')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'bill', '{"word":"bill","definition":"the paper that shows how much you must pay for your meal; in American English people often say check","example":"At the end of the meal Maya asks the waiter for the bill."}'::jsonb, 'ai_generated', 'validated', 'LO-3')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'bill'), 'multiple_choice', '{"prompt":"After dinner Maya asks the waiter for the paper with the price of the meal. What does she ask for?","options":["the menu","the daily special","the tip","the bill"],"correct_index":3}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'tip', '{"word":"tip","definition":"extra money that you leave for the waiter because the service is good","example":"She puts a small tip on the table."}'::jsonb, 'ai_generated', 'validated', 'LO-3')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'tip'), 'fill_blank', '{"sentence_with_blank":"The waiter smiles, because Maya leaves a good ___ on the table for him.","accepted_answers":["tip"]}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'tip'), 'multiple_choice', '{"prompt":"Maya pays her twenty euros for the meal. She puts two more euros on the plate for the waiter. What are the two extra euros?","options":["the bill","a tip","the daily special","a side dish"],"correct_index":1}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'split the bill', '{"word":"split the bill","definition":"to pay for a meal together, with each person paying part of it","example":"They split the bill, so each friend pays twenty euros."}'::jsonb, 'ai_generated', 'validated', 'LO-3')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
