insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'split the bill'), 'multiple_choice', '{"prompt":"The bill is forty euros, and each friend pays twenty euros of it. What do the friends do?","options":["They split the bill.","They book a table for two.","They order a side dish.","They ask the waiter to recommend a dish."],"correct_index":0}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'cash', '{"word":"cash","definition":"paper money and coins that you can hold in your hand, not a card","example":"Maya pays her half in cash."}'::jsonb, 'ai_generated', 'validated', 'LO-3')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'cash'), 'fill_blank', '{"sentence_with_blank":"Maya does not want to use her card, so she pays her half in ___.","accepted_answers":["cash"]}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;
insert into public.knowledge_items (content_unit_id, kind, dedup_key, data, origin, status, objective_id)
values ((select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two'), 'vocabulary', 'pay by card', '{"word":"pay by card","definition":"to pay with a bank card instead of paper money and coins","example":"Tom has no cash, so he asks if he can pay by card."}'::jsonb, 'ai_generated', 'validated', 'LO-3')
on conflict (content_unit_id, kind, dedup_key) do update set data = excluded.data, status = excluded.status, objective_id = excluded.objective_id;
insert into public.generated_exercises (knowledge_item_id, type, payload, status, objective_id)
values ((select ki.id from public.knowledge_items ki where ki.content_unit_id = (select cu.id from public.content_units cu where cu.source_id = (select id from public.content_sources where source_url = 'yuny://authored/en/v1') and cu.external_id = 'authored-ordering-dinner-for-two') and ki.kind = 'vocabulary' and ki.dedup_key = 'pay by card'), 'fill_blank', '{"sentence_with_blank":"Tom has no paper money and no coins, so he pays by ___.","accepted_answers":["card","bank card","credit card","debit card"]}'::jsonb, 'validated', 'LO-3')
on conflict (knowledge_item_id, type) do update set payload = excluded.payload, status = excluded.status, objective_id = excluded.objective_id;

